concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  changes:
    outputs:
      internal_poetry_packages: ${{ steps.changes.outputs.internal_poetry_packages
        }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: '# This list is duplicated in `pipelines/airbyte_ci/test/__init__.py`

          internal_poetry_packages:

          - airbyte-ci/connectors/pipelines/**

          - airbyte-ci/connectors/base_images/**

          - airbyte-ci/connectors/common_utils/**

          - airbyte-ci/connectors/connectors_insights/**

          - airbyte-ci/connectors/connector_ops/**

          - airbyte-ci/connectors/connectors_qa/**

          - airbyte-ci/connectors/ci_credentials/**

          - airbyte-ci/connectors/metadata_service/lib/**

          - airbyte-ci/connectors/metadata_service/orchestrator/**

          - airbyte-cdk/python/**

          - airbyte-integrations/bases/connector-acceptance-test/**

          '
  run-tests:
    if: needs.changes.outputs.internal_poetry_packages == 'true' && github.event.pull_request.head.repo.fork
      != true
    name: Internal Poetry packages CI
    needs: changes
    permissions:
      pull-requests: read
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - continue-on-error: true
      id: extract_branch
      if: github.event_name == 'workflow_dispatch'
      name: Extract branch name [WORKFLOW DISPATCH]
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      id: fetch_last_commit_id_pr
      if: github.event_name == 'pull_request'
      name: Fetch last commit id from remote branch [PULL REQUESTS]
      run: echo "commit_id=$(git ls-remote --heads origin ${{ github.head_ref }} |
        cut -f 1)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      id: fetch_last_commit_id_wd
      if: github.event_name == 'workflow_dispatch'
      name: Fetch last commit id from remote branch [WORKFLOW DISPATCH]
      run: echo "commit_id=$(git rev-parse origin/${{ steps.extract_branch.outputs.branch
        }})" >> $GITHUB_OUTPUT
    - continue-on-error: true
      id: run-airbyte-ci-test-pr
      if: github.event_name == 'pull_request'
      name: Run poe tasks for modified internal packages [PULL REQUEST]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        git_branch: ${{ github.head_ref }}
        git_revision: ${{ steps.fetch_last_commit_id_pr.outputs.commit_id }}
        github_token: ${{ secrets.GH_PAT_MAINTENANCE_OSS }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: test --modified
    - continue-on-error: true
      id: run-airbyte-ci-test-workflow-dispatch
      if: github.event_name == 'workflow_dispatch'
      name: Run poe tasks for requested internal packages [WORKFLOW DISPATCH]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: manual
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        git_branch: ${{ steps.extract_branch.outputs.branch }}
        git_revision: ${{ steps.fetch_last_commit_id_pr.outputs.commit_id }}
        github_token: ${{ secrets.GH_PAT_MAINTENANCE_OSS }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: test ${{ inputs.airbyte_ci_subcommand}}
name: Internal Poetry packages CI
on:
  repository_dispatch:
    types: trigger-ga___airbyte-ci-tests.yml
