jobs:
  approve-regression-tests:
    name: Approve Regression Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: job-vars
      name: Get job variables
      run: 'PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.inputs.pr
        }})

        echo "PR_JSON: $PR_JSON"

        echo "repo=$(echo "$PR_JSON" | jq -r .head.repo.full_name)" >> $GITHUB_OUTPUT

        BRANCH=$(echo "$PR_JSON" | jq -r .head.ref)

        echo "branch=$BRANCH" >> $GITHUB_OUTPUT

        echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        >> $GITHUB_OUTPUT

        LATEST_COMMIT=$(gh api repos/${{ github.repository }}/commits/$BRANCH | jq
        -r .sha)

        echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      id: first-comment-action
      name: Append comment with job run link
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: '

          > [Check job output.][1]


          [1]: ${{ steps.job-vars.outputs.run-url }}

          '
        comment-id: ${{ github.event.inputs.comment-id }}
        issue-number: ${{ github.event.inputs.pr }}
    - continue-on-error: true
      id: approve
      name: Approve regression tests
      run: "echo \"approving ....\"\nresponse=$(curl --write-out '%{http_code}' --silent\
        \ --output /dev/null \\\n  --request POST \\\n  --url ${{ github.api_url }}/repos/${{\
        \ github.repository }}/statuses/${{ steps.job-vars.outputs.latest_commit }}\
        \ \\\n  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \\\n\
        \  --header 'content-type: application/json' \\\n  --data '{\n    \"state\"\
        : \"success\",\n    \"context\": \"Regression Test Results Reviewed and Approved\"\
        ,\n    \"target_url\": \"https://github.com/airbytehq/airbyte/tree/master/airbyte-ci/connectors/live-tests\"\
        \n  }')\nif [ $response -ne 201 ]; then\n  echo \"Failed to approve regression\
        \ tests. HTTP status code: $response\"\n  exit 1\nelse\n  echo \"Regression\
        \ tests approved.\"\nfi\n"
    - continue-on-error: true
      if: success()
      name: Append success comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: "> \u2705 Approving regression tests\n"
        comment-id: ${{ steps.first-comment-action.outputs.comment-id }}
        reactions: '+1'
    - continue-on-error: true
      if: failure()
      name: Append failure comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: "> \u274C Regression test approval failed\n"
        comment-id: ${{ steps.first-comment-action.outputs.comment-id }}
        reactions: confused
name: Approve Regression Tests
on:
  repository_dispatch:
    types: trigger-ga___approve-regression-tests-command.yml
permissions:
  pull-requests: write
  statuses: write
run-name: 'Approve Regression Tests #${{ github.event.inputs.pr }}'
