jobs:
  approveAndMergeDispatch:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: scd
      name: Auto Approve Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v3
      with:
        commands: 'approve-and-merge

          '
        dispatch-type: repository
        issue-type: pull-request
        permission: admin
        repository: airbytehq/airbyte-platform-internal
        token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}
    - continue-on-error: true
      if: steps.scd.outputs.error-message
      name: Edit comment with error message
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '> Error!: ${{ steps.scd.outputs.error-message }}

          '
        comment-id: ${{ github.event.comment.id }}
    - continue-on-error: true
      id: checkout
      if: failure() || steps.scd.outputs.error-message
      name: Checkout Airbyte
      uses: actions/checkout@v2
    - continue-on-error: true
      id: repo_admins
      if: failure() || steps.scd.outputs.error-message
      name: Run get_repo_admins.sh
      run: 'echo "REPO_ADMINS=$(./tools/bin/get_repo_admins.sh ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA
        }} airbytehq/airbyte)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: failure() || steps.scd.outputs.error-message
      name: Edit comment with repo admins
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '>

          > Important: This command can only be run by one of the repository admins:

          > ${{ env.REPO_ADMINS }}

          '
        comment-id: ${{ github.event.comment.id }}
name: Approve and Merge Command Dispatch
on:
  repository_dispatch:
    types: trigger-ga___approve-and-merge-dispatch.yml
