jobs:
  run_auto_merge:
    name: Run auto-merge
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Install and configure Poetry
      uses: snok/install-poetry@v1
    - continue-on-error: true
      env:
        AUTO_MERGE_PRODUCTION: ${{ vars.ENABLE_CONNECTOR_AUTO_MERGE }}
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_GITHUB_TOKEN }}
      name: Run auto merge
      run: 'poetry install

        poetry run auto-merge

        '
      shell: bash
      working-directory: airbyte-ci/connectors/auto_merge
name: Auto merge connector PRs Cron
on:
  repository_dispatch:
    types: trigger-ga___auto_merge.yml
