concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
jobs:
  connectors_early_ci:
    env:
      MAIN_BRANCH_NAME: master
    environment: community-ci-auto
    if: github.event.pull_request.head.repo.fork == true
    name: Run connectors early CI on fork
    needs: fail_on_protected_path_changes
    permissions:
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - continue-on-error: true
      id: pull_github_folder
      name: Pull .github folder from main repository
      run: 'git remote add main https://github.com/airbytehq/airbyte.git

        git fetch main ${MAIN_BRANCH_NAME}

        git checkout main/${MAIN_BRANCH_NAME} -- .github

        git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci

        '
    - continue-on-error: true
      name: Run airbyte-ci static checks and version increment checks on modified
        connectors
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        git_branch: ${{ github.head_ref }}
        git_repo_url: ${{ github.event.pull_request.head.repo.clone_url }}
        git_revision: ${{ github.event.pull_request.head.sha }}
        github_token: ${{ github.token }}
        is_fork: 'true'
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors --modified test --only-step=qa_checks --only-step=version_inc_check
          --global-status-check-context='Connectors early CI checks' --global-status-check-description='Running
          early CI checks on connectors'
    - continue-on-error: true
      id: upload-artifact
      name: Upload pipeline reports
      uses: actions/upload-artifact@v4
      with:
        name: early-ci-pipeline-reports
        path: /home/runner/work/airbyte/airbyte/airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/connectors/test/pull_request/**/output.html
        retention-days: 7
    timeout-minutes: 10
  connectors_full_ci:
    env:
      MAIN_BRANCH_NAME: master
    environment: community-ci
    if: github.event.pull_request.head.repo.fork == true
    name: Run connectors full CI on fork
    needs: fail_on_protected_path_changes
    permissions:
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - continue-on-error: true
      id: pull_github_folder
      name: Pull .github folder from main repository
      run: 'git remote add main https://github.com/airbytehq/airbyte.git

        git fetch main ${MAIN_BRANCH_NAME}

        git checkout main/${MAIN_BRANCH_NAME} -- .github

        git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci

        '
    - continue-on-error: true
      name: Run airbyte-ci connectors test
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ github.head_ref }}
        git_repo_url: ${{ github.event.pull_request.head.repo.clone_url }}
        git_revision: ${{ github.event.pull_request.head.sha }}
        github_token: ${{ github.token }}
        is_fork: 'true'
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors --modified test
    - continue-on-error: true
      id: upload-artifact
      name: Upload pipeline reports
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-reports
        path: /home/runner/work/airbyte/airbyte/airbyte-ci/connectors/pipelines/pipeline_reports/airbyte-ci/connectors/test/pull_request/**/output.html
        retention-days: 7
    timeout-minutes: 180
  fail_on_protected_path_changes:
    if: github.event.pull_request.head.repo.fork == true
    name: Check fork do not change protected paths
    permissions:
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: check_for_changes_in_protected_paths
      name: Check for changes in protected paths
      uses: dorny/paths-filter@v2
      with:
        filters: "protected_paths:\n  - '.github/**'\n"
    - continue-on-error: true
      if: steps.check_for_changes_in_protected_paths.outputs.protected_paths == 'true'
      name: Fail if changes in protected paths
      run: 'echo "The fork has changes in protected paths. This is not allowed."

        exit 1

        '
  format_check:
    env:
      MAIN_BRANCH_NAME: master
    environment: community-ci-auto
    if: github.event.pull_request.head.repo.fork == true
    name: Check for formatting errors
    needs: fail_on_protected_path_changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - continue-on-error: true
      id: pull_github_folder
      name: Pull .github folder and internal packages from main repository
      run: 'git remote add main https://github.com/airbytehq/airbyte.git

        git fetch main ${MAIN_BRANCH_NAME}

        git checkout main/${MAIN_BRANCH_NAME} -- .github

        git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci

        '
    - continue-on-error: true
      name: Run airbyte-ci format check all
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        is_fork: 'true'
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: format check all
    timeout-minutes: 30
  internal_poetry_packages_ci:
    env:
      MAIN_BRANCH_NAME: master
    environment: community-ci
    if: github.event.pull_request.head.repo.fork == true
    name: Internal Poetry packages CI
    needs: fail_on_protected_path_changes
    permissions:
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - continue-on-error: true
      id: pull_github_folder
      name: Pull .github folder from main repository
      run: 'git remote add main https://github.com/airbytehq/airbyte.git

        git fetch main ${MAIN_BRANCH_NAME}

        git checkout main/${MAIN_BRANCH_NAME} -- .github

        git checkout main/${MAIN_BRANCH_NAME} -- airbyte-ci

        '
    - continue-on-error: true
      id: run-airbyte-ci-test-pr
      name: Run poe tasks for modified internal packages [PULL REQUEST]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        git_branch: ${{ github.head_ref }}
        git_repo_url: ${{ github.event.pull_request.head.repo.clone_url }}
        git_revision: ${{ github.event.pull_request.head.sha }}
        github_token: ${{ github.token }}
        is_fork: 'true'
        subcommand: test --modified
    timeout-minutes: 180
name: Community CI
on:
  repository_dispatch:
    types: trigger-ga___community_ci.yml
