jobs:
  connectors_insights:
    name: Connectors Insights generation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Docker login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    - continue-on-error: true
      name: Get Dagger Engine Image
      uses: ./.github/actions/get-dagger-engine-image
      with:
        dagger_engine_image: registry.dagger.io/engine:v0.9.6
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - continue-on-error: true
      name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        installer-parallel: true
        virtualenvs-create: true
        virtualenvs-in-project: true
    - continue-on-error: true
      id: cached-poetry-dependencies
      name: Load cached venv
      uses: actions/cache@v3
      with:
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{
          hashFiles('**/poetry.lock') }}
        path: .venv
    - continue-on-error: true
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      name: Install dependencies
      run: poetry -C airbyte-ci/connectors/connectors_insights install --no-interaction
        --no-root
    - continue-on-error: true
      name: Install project
      run: poetry -C airbyte-ci/connectors/connectors_insights install --no-interaction
    - continue-on-error: true
      env:
        GCP_SA_KEY: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
      name: Write Google service account key to file
      run: echo "$GCP_SA_KEY" > $HOME/gcp-sa-key.json
    - continue-on-error: true
      name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-sa-key.json" >> $GITHUB_ENV
    - continue-on-error: true
      name: Run connectors insights
      run: 'poetry -C airbyte-ci/connectors/connectors_insights run connectors-insights
        generate --gcs-uri=gs://prod-airbyte-cloud-connector-metadata-service/connector_insights
        --connector-directory airbyte-integrations/connectors/ --concurrency 10 ${{
        inputs.rewrite == ''true'' && ''--rewrite'' || ''''}}

        '
    timeout-minutes: 1440
name: Connectors Insights
on:
  repository_dispatch:
    types: trigger-ga___connectors_insights.yml
