jobs:
  test_connectors:
    name: 'Test connectors: ${{ inputs.test-connectors-options || ''nightly build
      for Certified connectors'' }}'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      id: extract_branch
      name: Extract branch name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Test connectors
      uses: ./.github/actions/run-airbyte-ci
      with:
        ci_job_key: nightly_builds
        context: master
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ steps.extract_branch.outputs.branch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors ${{ inputs.test-connectors-options || '--concurrency=8
          --support-level=certified' }} test
    timeout-minutes: 720
name: Connector Ops CI - Connectors Nightly Tests
on:
  repository_dispatch:
    types: trigger-ga___connectors_nightly_build.yml
run-name: 'Test connectors: ${{ inputs.test-connectors-options || ''nightly build
  for Certified connectors'' }}'
