jobs:
  check-review-requirements:
    if: ${{ github.event.pull_request.head.repo.fork == false && github.event.pull_request.draft
      == false }}
    name: Check if a review is required from Connector teams
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Install ci-connector-ops package
      run: 'pip install pipx

        pipx ensurepath

        pipx install airbyte-ci/connectors/connector_ops

        '
    - continue-on-error: true
      id: write-review-requirements-file
      name: Write review requirements file
      run: write-review-requirements-file >> $GITHUB_OUTPUT
    - continue-on-error: true
      id: get-mandatory-reviewers
      name: Get mandatory reviewers
      run: print-mandatory-reviewers >> $GITHUB_OUTPUT
    - continue-on-error: true
      if: steps.write-review-requirements-file.outputs.CREATED_REQUIREMENTS_FILE ==
        'true'
      name: Check if the review requirements are met
      uses: Automattic/action-required-review@v3
      with:
        request-reviews: true
        requirements-file: .github/connector_org_review_requirements.yaml
        status: ${{ steps.get-mandatory-reviewers.outputs.MANDATORY_REVIEWERS  }}
        token: ${{ secrets.OCTAVIA_4_ROOT_ACCESS }}
name: Connector Ops CI - Check review requirements
on:
  repository_dispatch:
    types: trigger-ga___connector_teams_review_requirements.yml
