env:
  CODE_FREEZE_END_DATE: '2024-01-02'
  CODE_FREEZE_START_DATE: '2023-12-21'
jobs:
  code-freeze-check:
    name: Code freeze check
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: check-code-freeze-in-effect
      name: Check code freeze in effect
      run: "start_date=$(date -d \"$CODE_FREEZE_START_DATE\" +%s)\nend_date=$(date\
        \ -d \"$CODE_FREEZE_END_DATE\" +%s)\ncurrent_date=$(date +%s)\n\nif [ \"$current_date\"\
        \ -ge \"$start_date\" ] && [ \"$current_date\" -le \"$end_date\" ]; then\n\
        \    echo \"Code freeze is in effect\"\n    echo \"::set-output name=is_in_code_freeze::true\"\
        \nelse\n    echo \"Code freeze is not in effect\"\n    echo \"::set-output\
        \ name=is_in_code_freeze::false\"\nfi\n"
    - continue-on-error: true
      id: changed-files
      if: steps.check-code-freeze-in-effect.outputs.is_in_code_freeze == 'true'
      name: Get changed files
      uses: tj-actions/changed-files@v44
      with:
        files_yaml: "connectors:\n  - 'airbyte-integrations/connectors/**'\n  - '!**/*.md'\n"
    - continue-on-error: true
      if: steps.changed-files.outputs.connectors_any_changed == 'true' && steps.check-code-freeze-in-effect.outputs.is_in_code_freeze
        == 'true'
      name: Code freeze comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: code_freeze_warning
        message: "> [!WARNING]\n> <b>\U0001F6A8 Connector code freeze is in effect\
          \ until ${{ env.CODE_FREEZE_END_DATE }}. This PR is changing connector code.\
          \ Please contact the current OC engineers if you want to merge this change\
          \ to master.</b>\n"
    - continue-on-error: true
      if: steps.changed-files.outputs.connectors_any_changed == 'false' && steps.check-code-freeze-in-effect.outputs.is_in_code_freeze
        == 'true'
      name: Code freeze comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: code_freeze_warning
        message: '> [!WARNING]

          > <b>Soft code freeze is in effect until ${{ env.CODE_FREEZE_END_DATE }}.
          Please avoid merging to master. #freedom-and-responsibility</b>

          '
    - continue-on-error: true
      if: steps.changed-files.outputs.connectors_any_changed == 'true' && steps.check-code-freeze-in-effect.outputs.is_in_code_freeze
        == 'true'
      name: Fail workflow if connector code has been changed
      run: echo "Connector code freeze is in effect. Please contact the current OC
        engineers if you want to merge this change." && exit 1
name: Code freeze
on:
  repository_dispatch:
    types: trigger-ga___connector_code_freeze.yml
