concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  changes:
    outputs:
      connectors: ${{ steps.changes.outputs.connectors }}
    permissions:
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: "connectors:\n  - '*'\n  - 'airbyte-ci/**/*'\n  - 'airbyte-integrations/connectors/**/*'\n\
          \  - 'airbyte-cdk/java/**/*'\n  - 'buildSrc/**/*'\n"
    - continue-on-error: true
      if: steps.changes.outputs.connectors != 'true' && github.event_name == 'pull_request'
      name: Skip Connectors CI tests
      run: "curl --request POST \\\n--url https://api.github.com/repos/${{ github.repository\
        \ }}/statuses/${{ github.event.pull_request.head.sha }} \\\n--header 'authorization:\
        \ Bearer ${{ secrets.GITHUB_TOKEN }}' \\\n--header 'content-type: application/json'\
        \ \\\n--data '{\n  \"state\": \"success\",\n  \"context\": \"Connectors CI\
        \ tests\",\n  \"target_url\": \"${{ github.event.workflow_run.html_url }}\"\
        \n  }' \\\n"
  connectors_ci:
    if: (github.event_name == 'pull_request' && needs.changes.outputs.connectors ==
      'true' && github.event.pull_request.head.repo.fork != true) || github.event_name
      == 'workflow_dispatch'
    name: Connectors CI
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Check PAT rate limits
      run: "./tools/bin/find_non_rate_limited_PAT \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_OSS\
        \ }} \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}\n"
    - continue-on-error: true
      id: extract_branch
      if: github.event_name == 'workflow_dispatch'
      name: Extract branch name [WORKFLOW DISPATCH]
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      id: fetch_last_commit_id_pr
      if: github.event_name == 'pull_request'
      name: Fetch last commit id from remote branch [PULL REQUESTS]
      run: echo "commit_id=$(git ls-remote --heads origin ${{ github.head_ref }} |
        cut -f 1)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      id: fetch_last_commit_id_wd
      if: github.event_name == 'workflow_dispatch'
      name: Fetch last commit id from remote branch [WORKFLOW DISPATCH]
      run: echo "commit_id=$(git rev-parse origin/${{ steps.extract_branch.outputs.branch
        }})" >> $GITHUB_OUTPUT
    - continue-on-error: true
      if: github.event_name == 'workflow_dispatch'
      name: Test connectors [WORKFLOW DISPATCH]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: manual
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ steps.extract_branch.outputs.branch }}
        git_revision: ${{ steps.fetch_last_commit_id_wd.outputs.commit_id }}
        github_token: ${{ env.PAT }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors ${{ github.event.inputs.test-connectors-options }}
          test
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Test connectors [PULL REQUESTS]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ github.head_ref }}
        git_revision: ${{ steps.fetch_last_commit_id_pr.outputs.commit_id }}
        github_token: ${{ env.PAT }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors --execute-timeout=18000 --modified  test
    timeout-minutes: 360
name: Connectors Tests
on:
  repository_dispatch:
    types: trigger-ga___connectors_tests.yml
