jobs:
  test_connectors:
    name: 'Test connectors: ${{ inputs.test-connectors-options || ''weekly build for
      Community connectors'' }}'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      id: extract_branch
      name: Extract branch name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      shell: bash
    - continue-on-error: true
      name: Test connectors
      uses: ./.github/actions/run-airbyte-ci
      with:
        ci_job_key: weekly_alpha_test
        context: master
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ steps.extract_branch.outputs.branch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        subcommand: --show-dagger-logs connectors ${{ inputs.test-connectors-options
          || '--concurrency=3 --metadata-query="(data.ab_internal.ql > 100) & (data.ab_internal.sl
          < 200)"' }} test
    timeout-minutes: 8640
name: Connector Ops CI - Connectors Weekly Tests
on:
  repository_dispatch:
    types: trigger-ga___connectors_weekly_build.yml
run-name: 'Test connectors: ${{ inputs.test-connectors-options || ''weekly build for
  Community connectors'' }}'
