concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}
jobs:
  connectors_up_to_date:
    name: Connectors up-to-date
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      id: airbyte-ci-connectors-up-to-date
      name: Run airbyte-ci connectors up-to-date
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: master
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        github_token: ${{ secrets.AUTO_MERGE_GITHUB_TOKEN }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors  ${{ github.event.inputs.connectors-options || '--concurrency=10
          --language=python --language=low-code' }} up-to-date --create-prs ${{ github.event.inputs.auto-merge
          == 'false' && '' || '--auto-merge' }}
    timeout-minutes: 1440
name: Connectors up-to-date
on:
  repository_dispatch:
    types: trigger-ga___connectors_up_to_date.yml
