concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  connectors_ci:
    if: github.event.pull_request.head.repo.fork != true
    name: Connectors Version Increment Check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Check PAT rate limits
      run: "./tools/bin/find_non_rate_limited_PAT \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_OSS\
        \ }} \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}\n"
    - continue-on-error: true
      id: fetch_last_commit_id_pr
      if: github.event_name == 'pull_request'
      name: Fetch last commit id from remote branch [PULL REQUESTS]
      run: echo "commit_id=$(git ls-remote --heads origin ${{ github.head_ref }} |
        cut -f 1)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Test connectors [PULL REQUESTS]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        git_branch: ${{ github.head_ref }}
        git_revision: ${{ steps.fetch_last_commit_id_pr.outputs.commit_id }}
        github_token: ${{ env.PAT }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: connectors --modified test --only-step=version_inc_check --global-status-check-context='Version
          increment check for Java connectors' --global-status-check-description='Checking
          if java connectors modified in this PR got their version bumped'
    timeout-minutes: 12
name: Connectors Version Increment Check
on:
  repository_dispatch:
    types: trigger-ga___connectors_version_increment_check.yml
