jobs:
  check-review-requirements:
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    name: Check if a review is required from Connector teams
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: actorTeams
      name: Check contributor team membership
      uses: tspascoal/get-user-teams-membership@v3
      with:
        GITHUB_TOKEN: ${{ secrets.OCTAVIA_4_ROOT_ACCESS }}
        username: ${{ github.actor }}
    - continue-on-error: true
      if: ${{ (contains(steps.actorTeams.outputs.teams, 'community-contractor')) }}
      name: Check if the review requirements are met
      uses: Automattic/action-required-review@v3
      with:
        fail: true
        request-reviews: true
        requirements: "- paths:\n    - \"airbyte-integrations/connectors/source-**\"\
          \n    - \"airbyte-integrations/connectors/destination-**\"\n  teams:\n \
          \   - dev-marketplace-contributions\n"
        status: Required review
        token: ${{ secrets.OCTAVIA_4_ROOT_ACCESS }}
name: Connector Ops CI - Check contractors review requirements
on:
  repository_dispatch:
    types: trigger-ga___contractors_review_requirements.yml
