jobs:
  format-check:
    if: github.event.pull_request.head.repo.fork != true
    name: Check for formatting errors
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte (with credentials)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}
    - continue-on-error: true
      id: airbyte_ci_format_check_all_master
      if: github.ref == 'refs/heads/master'
      name: Run airbyte-ci format check [MASTER]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: master
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: format check all
    - continue-on-error: true
      id: airbyte_ci_format_check_all_pr
      if: github.event_name == 'pull_request'
      name: Run airbyte-ci format check [PULL REQUEST]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: pull_request
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: format check all
    - continue-on-error: true
      id: airbyte_ci_format_check_all_manual
      if: github.event_name == 'workflow_dispatch'
      name: Run airbyte-ci format check [WORKFLOW DISPATCH]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: manual
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        subcommand: format check all
    - continue-on-error: true
      env:
        AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: match-github-to-slack-user
      if: github.ref == 'refs/heads/master'
      name: Match GitHub User to Slack User [MASTER]
      uses: ./.github/actions/match-github-to-slack-user
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: steps.airbyte_ci_format_check_all_master.outcome == 'failure' && github.ref
        == 'refs/heads/master'
      name: Format Failure on Master Slack Channel [MASTER]
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C03BEADRPNY\", \"blocks\":[ {\"type\":\"divider\"},
          {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Formatting
          is broken on master! :bangbang: \n\n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged
          by_: *${{ github.actor }}* \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{
          steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"
          :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View
          Action Run> :octavia-shocked: \n\"}}, {\"type\":\"divider\"}]}'
name: Check for formatting errors
on:
  repository_dispatch:
    types: trigger-ga___format_check.yml
run-name: Check for formatting errors on ${{ github.ref }}
