concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
jobs:
  changes:
    outputs:
      java: ${{ steps.changes.outputs.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: "java:\n  - '**/*.java'\n  - '**/*.gradle'\n  - '**/*.kt'\n  - 'airbyte-cdk/java/**/*'\n"
  notify-failure-slack-channel:
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    name: Notify Slack Channel on Build Failures
    needs:
    - run-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: match-github-to-slack-user
      name: Match GitHub User to Slack User
      uses: ./.github/actions/match-github-to-slack-user
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      name: Publish to OSS Build Failure Slack Channel
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C03BEADRPNY\", \"blocks\":[ {\"type\":\"divider\"},
          {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" Merge to
          OSS Master failed! :bangbang: \n\n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged
          by_: *${{ github.actor }}* \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{
          steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"
          :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View
          Action Run> :octavia-shocked: \n\"}}, {\"type\":\"divider\"}]}'
  notify-failure-slack-channel-fixed-broken-build:
    if: ${{ success() && github.event.pull_request.head.repo.fork != true }}
    name: Notify Slack Channel on Build Fixes
    needs:
    - run-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: last_status
      name: Get Previous Workflow Status
      uses: Mercymeilya/last-workflow-status@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ steps.last_status.outputs.last_status == 'failure' }}
      name: Publish Build Fixed Message to OSS Build Failure Slack Channel
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C03BEADRPNY\", \"blocks\":[ {\"type\":\"divider\"},
          {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" OSS Master
          Fixed! :white_check_mark: \n\n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged
          by_: *${{ github.actor }}* \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"
          :octavia-rocket: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View
          Action Run> :octavia-rocket: \n\"}}, {\"type\":\"divider\"}]}'
  run-check:
    if: needs.changes.outputs.java == 'true'
    name: Gradle Check
    needs:
    - changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      if: github.event.pull_request.head.repo.fork != true
      name: Docker login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    - continue-on-error: true
      env:
        CI: true
      name: Run Gradle Check
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --scan check -DskipSlowTests=true
        concurrent: true
        gradle-distribution-sha-256-sum-warning: false
        job-id: gradle-check
        read-only: ${{ github.ref != 'refs/heads/master' }}
    timeout-minutes: 30
  set-instatus-incident-on-failure:
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    name: Create Instatus Incident on Failure
    needs:
    - run-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Call Instatus Webhook
      uses: joelwmale/webhook-action@master
      with:
        body: '{ "trigger": "down", "status": "HASISSUES" }'
        url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
  set-instatus-incident-on-success:
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    name: Create Instatus Incident on Success
    needs:
    - run-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Call Instatus Webhook
      uses: joelwmale/webhook-action@master
      with:
        body: '{ "trigger": "up" }'
        url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
name: Connector Ops CI - Gradle Check
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
