jobs:
  add-label-based-on-file-changes:
    name: Label PRs based on files changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Label PR based on changed files
      uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
        sync-labels: true
name: Label PR based on filepath
on:
  repository_dispatch:
    types: trigger-ga___label-github-issues-by-path.yml
