jobs:
  connector_metadata_service_deploy_orchestrator:
    name: Connector metadata service deploy orchestrator
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        DAGSTER_CLOUD_DEPLOYMENT: prod
        DAGSTER_CLOUD_METADATA_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_METADATA_API_TOKEN
          }}
      id: metadata-orchestrator-deploy-orchestrator-pipeline-prod
      if: github.event_name == 'push'
      name: Deploy the metadata orchestrator [On merge to master]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: master
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        subcommand: metadata deploy orchestrator
    - continue-on-error: true
      env:
        DAGSTER_CLOUD_DEPLOYMENT: ${{ inputs.deployment_target }}
        DAGSTER_CLOUD_METADATA_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_METADATA_API_TOKEN
          }}
      id: metadata-orchestrator-deploy-orchestrator-pipeline-branch
      if: github.event_name == 'workflow_dispatch'
      name: Deploy the metadata orchestrator [On workflow]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: manual
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        subcommand: metadata deploy orchestrator
name: Connector Ops CI - Metadata Service Deploy Orchestrator
on:
  repository_dispatch:
    types: trigger-ga___metadata_service_deploy_orchestrator_dagger.yml
