concurrency:
  cancel-in-progress: false
  group: publish-airbyte-cdk
jobs:
  build-cdk:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      id: install_poetry
      name: Install Poetry
      uses: snok/install-poetry@v1
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      id: install_dependencies
      name: Install Dependencies
      run: poetry install
      working-directory: airbyte-cdk/python
    - continue-on-error: true
      name: Build CDK Package
      run: poetry run poe build
      working-directory: airbyte-cdk/python
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ failure() }}
      name: Post failure to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"Error during `build-cdk` while publishing Python\
          \ CDK!\",\n    \"blocks\": [\n        {\n            \"type\": \"section\"\
          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
          \            \"text\": \"Error while publishing Python CDK!\"\n        \
          \    }\n        },\n        {\n            \"type\": \"section\",\n    \
          \        \"text\": {\n                \"type\": \"mrkdwn\",\n          \
          \      \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
  bump-manifest-source:
    name: Bump CDK dependency of source-declarative-manifest
    needs:
    - bump-version
    - publish-cdk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      id: install_poetry
      name: Install Poetry
      uses: snok/install-poetry@v1
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
        token: ${{ secrets.GH_PAT_MAINTENANCE_OSS }}
    - continue-on-error: true
      name: Bump CDK dependency of source-declarative-manifest
      run: "cd airbyte-integrations/connectors/source-declarative-manifest\necho \"\
        Attempting to pull the newly published version of airbyte-cdk.\"\nwhile true;\
        \ do\n  # --no-cache to force looking for the new version\n  poetry add airbyte-cdk==${{needs.bump-version.outputs.new_cdk_version}}\
        \ --no-cache && break\n  # Loop to wait for the new version to be available\
        \ to poetry\n  echo \"Couldn't add new dependency. This is normal if the dependency\
        \ could not (yet) be found. Retrying in 10 seconds...\"\n  sleep 10\ndone\n\
        echo \"Successfully updated the CDK dependency of source-declarative-manifest\
        \ to ${{needs.bump-version.outputs.new_cdk_version}}\"\n"
      timeout-minutes: 10
    - continue-on-error: true
      name: Bump version of source-declarative-manifest
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: master
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        metadata_service_gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS
          }}
        python_registry_token: ${{ secrets.PYPI_TOKEN }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        slack_webhook_url: ${{ secrets.PUBLISH_ON_MERGE_SLACK_WEBHOOK }}
        spec_cache_gcs_credentials: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY_PUBLISH
          }}
        subcommand: connectors --concurrency=1 --execute-timeout=3600 --name=source-declarative-manifest
          bump-version ${{ github.event.inputs.release-type }} 'Bump CDK version to
          ${{needs.bump-version.outputs.new_cdk_version}}' --pr-number=36501
    - continue-on-error: true
      name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "\U0001F916 Cut version ${{needs.bump-version.outputs.new_cdk_version}}\
          \ of source-declarative-manifest"
        commit_user_email: octavia-squidington-iii@users.noreply.github.com
        commit_user_name: Octavia Squidington III
        file_pattern: docs/integrations/sources/low-code.md airbyte-integrations/connectors/source-declarative-manifest/*
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ failure() }}
      name: Post failure to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \":warning: A new version of Python CDK has been\
          \ released but `source-declarative-manifest` and Connector Builder haven't\
          \ been automatically updated\",\n    \"blocks\": [\n        {\n        \
          \    \"type\": \"section\",\n            \"text\": {\n                \"\
          type\": \"mrkdwn\",\n                \"text\": \"A new version of Python\
          \ CDK has been released with <https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/CHANGELOG.md|changelog>:\
          \ ${{ github.event.inputs.changelog-message }}\\n\\n\"\n            }\n\
          \        },\n        {\n            \"type\": \"section\",\n           \
          \ \"text\": {\n                \"type\": \"mrkdwn\",\n                \"\
          text\": \":warning: Could not bump version of `source-declarative-manifest`.>\\\
          n\"\n            }\n        },\n        {\n            \"type\": \"section\"\
          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
          \            \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
  bump-version:
    if: github.event.inputs.release-type != 'none'
    needs: build-cdk
    outputs:
      new_cdk_version: ${{ steps.bumpversion.outputs.NEW_VERSION }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      id: install_poetry
      name: Install Poetry
      uses: snok/install-poetry@v1
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
        token: ${{ secrets.GH_PAT_MAINTENANCE_OSS }}
    - continue-on-error: true
      id: bumpversion
      name: 'Publish Python CDK: bump Poetry package version'
      run: 'cd airbyte-cdk/python

        # Bump package version

        poetry version ${{ github.event.inputs.release-type }}

        new_version="$(poetry version -s)"

        awk -v NEW_VERSION="$new_version" -v CHANGELOG_MESSAGE="${{ github.event.inputs.changelog-message
        }}" ''NR==3{print "## " NEW_VERSION "\n" CHANGELOG_MESSAGE "\n"}1'' CHANGELOG.md
        > tmp && mv tmp CHANGELOG.md

        echo NEW_VERSION=$new_version >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "\U0001F916 ${{ github.event.inputs.release-type }} bump Python\
          \ CDK to version ${{ steps.bumpversion.outputs.NEW_VERSION }}"
        commit_user_email: octavia-squidington-iii@users.noreply.github.com
        commit_user_name: Octavia Squidington III
        file_pattern: airbyte-cdk/python/pyproject.toml airbyte-cdk/python/CHANGELOG.md
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ failure() }}
      name: Post failure to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"Error during `bump-version` while publishing\
          \ Python CDK!\",\n    \"blocks\": [\n        {\n            \"type\": \"\
          section\",\n            \"text\": {\n                \"type\": \"mrkdwn\"\
          ,\n                \"text\": \"Error while publishing Python CDK!\"\n  \
          \          }\n        },\n        {\n            \"type\": \"section\",\n\
          \            \"text\": {\n                \"type\": \"mrkdwn\",\n      \
          \          \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
  publish-cdk:
    name: Publish Python CDK to PyPi
    needs: bump-version
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.gitref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.0
      with:
        package_directory: airbyte-cdk/python
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        python_version: '3.10'
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ failure() }}
      name: Post failure to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"Error during `publish-cdk` while publishing Python\
          \ CDK!\",\n    \"blocks\": [\n        {\n            \"type\": \"section\"\
          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
          \            \"text\": \"Error while publishing Python CDK!\"\n        \
          \    }\n        },\n        {\n            \"type\": \"section\",\n    \
          \        \"text\": {\n                \"type\": \"mrkdwn\",\n          \
          \      \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
  update-connector-builder:
    needs:
    - bump-version
    - bump-manifest-source
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - continue-on-error: true
      name: Checkout Airbyte Platform Internal
      uses: actions/checkout@v3
      with:
        repository: airbytehq/airbyte-platform-internal
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
    - continue-on-error: true
      name: Update CDK version
      run: 'PREVIOUS_VERSION=$(cat oss/airbyte-connector-builder-resources/CDK_VERSION)

        sed -i "s/${PREVIOUS_VERSION}/${{needs.bump-version.outputs.new_cdk_version}}/g"
        oss/airbyte-connector-builder-server/Dockerfile

        sed -i "s/${PREVIOUS_VERSION}/${{needs.bump-version.outputs.new_cdk_version}}/g"
        cloud/airbyte-connector-builder-server-wrapped/Dockerfile

        sed -i "s/airbyte-cdk==${PREVIOUS_VERSION}/airbyte-cdk==${{needs.bump-version.outputs.new_cdk_version}}/g"
        oss/airbyte-connector-builder-server/requirements.in

        echo ${{needs.bump-version.outputs.new_cdk_version}} > oss/airbyte-connector-builder-resources/CDK_VERSION

        cd oss/airbyte-connector-builder-server

        pip install pip-tools

        pip-compile --upgrade

        '
    - continue-on-error: true
      id: create-pull-request
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        base: master
        body: This is an automatically generated PR triggered by a CDK release
        branch: automatic-cdk-release
        commit-message: 'chore: update CDK version following release'
        delete-branch: true
        title: 'chore: update CDK version following release'
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      name: Post success to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"A new version of Python CDK has been released!\"\
          ,\n    \"blocks\": [\n        {\n            \"type\": \"section\",\n  \
          \          \"text\": {\n                \"type\": \"mrkdwn\",\n        \
          \        \"text\": \"A new version of Python CDK has been released with\
          \ <https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/CHANGELOG.md|changelog>:\
          \ ${{ github.event.inputs.changelog-message }}\\n\\n\"\n            }\n\
          \        },\n        {\n            \"type\": \"section\",\n           \
          \ \"text\": {\n                \"type\": \"mrkdwn\",\n                \"\
          text\": \"A PR has also been created for the <${{ steps.create-pull-request.outputs.pull-request-url\
          \ }}|Connector Builder>\\n\"\n            }\n        },\n        {\n   \
          \         \"type\": \"section\",\n            \"text\": {\n            \
          \    \"type\": \"mrkdwn\",\n                \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ failure() }}
      name: Post failure to Slack channel dev-connectors-extensibility
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \":warning: A new version of Python CDK has been\
          \ released but Connector Builder hasn't been automatically updated\",\n\
          \    \"blocks\": [\n        {\n            \"type\": \"section\",\n    \
          \        \"text\": {\n                \"type\": \"mrkdwn\",\n          \
          \      \"text\": \"A new version of Python CDK has been released with <https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/CHANGELOG.md|changelog>:\
          \ ${{ github.event.inputs.changelog-message }}\\n\\n\"\n            }\n\
          \        },\n        {\n            \"type\": \"section\",\n           \
          \ \"text\": {\n                \"type\": \"mrkdwn\",\n                \"\
          text\": \":warning: Could not automatically create a PR for Connector Builder>\\\
          n\"\n            }\n        },\n        {\n            \"type\": \"section\"\
          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
          \            \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
name: Publish Python CDK Manually
on:
  repository_dispatch:
    types: trigger-ga___publish-cdk-command-manually.yml
