jobs:
  notify-failure-slack-channel:
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    name: Notify Slack Channel on Build Failures
    needs:
    - publish_connectors
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: match-github-to-slack-user
      name: Match GitHub User to Slack User
      uses: ./.github/actions/match-github-to-slack-user
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      name: Publish to OSS Build Failure Slack Channel
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C056HGD1QSW\", \"blocks\":[ {\"type\":\"divider\"},
          {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" Publish
          Connector Failed! :bangbang: \n\n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged
          by_: *${{ github.actor }}* \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{
          steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}}, {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"
          :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View
          Action Run> :octavia-shocked: \n\"}}, {\"type\":\"divider\"}]}'
  publish_connectors:
    name: Publish connectors
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v4
    - continue-on-error: true
      id: publish-modified-connectors
      if: github.event_name == 'push'
      name: Publish modified connectors [On merge to master]
      uses: ./.github/actions/run-airbyte-ci
      with:
        context: master
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        metadata_service_gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS
          }}
        python_registry_token: ${{ secrets.PYPI_TOKEN }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        slack_webhook_url: ${{ secrets.PUBLISH_ON_MERGE_SLACK_WEBHOOK }}
        spec_cache_gcs_credentials: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY_PUBLISH
          }}
        subcommand: connectors --concurrency=1 --execute-timeout=3600 --metadata-changes-only
          publish --main-release
    - continue-on-error: true
      id: publish-connectors
      if: github.event_name == 'workflow_dispatch'
      name: Publish connectors [manual]
      uses: ./.github/actions/run-airbyte-ci
      with:
        airbyte_ci_binary_url: ${{ github.event.inputs.airbyte_ci_binary_url }}
        context: manual
        dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN_2 }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
        gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
        gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        metadata_service_gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS
          }}
        python_registry_token: ${{ secrets.PYPI_TOKEN }}
        s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
        slack_webhook_url: ${{ secrets.PUBLISH_ON_MERGE_SLACK_WEBHOOK }}
        spec_cache_gcs_credentials: ${{ secrets.SPEC_CACHE_SERVICE_ACCOUNT_KEY_PUBLISH
          }}
        subcommand: connectors ${{ github.event.inputs.connectors-options }} publish
          ${{ github.event.inputs.publish-options }}
  set-instatus-incident-on-failure:
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    name: Create Instatus Incident on Failure
    needs:
    - publish_connectors
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Call Instatus Webhook
      uses: joelwmale/webhook-action@master
      with:
        body: '{ "trigger": "down", "status": "HASISSUES" }'
        url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
  set-instatus-incident-on-success:
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    name: Create Instatus Incident on Success
    needs:
    - publish_connectors
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Call Instatus Webhook
      uses: joelwmale/webhook-action@master
      with:
        body: '{ "trigger": "up" }'
        url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
name: Connector Ops CI - Publish Connectors
on:
  repository_dispatch:
    types: trigger-ga___publish_connectors.yml
