concurrency:
  cancel-in-progress: false
  group: publish-java-cdk
env:
  CDK_VERSION_FILE_PATH: ./airbyte-cdk/java/airbyte-cdk/core/src/main/resources/version.properties
  DRY_RUN: ${{ github.event_name == 'push' && 'false' || github.event.inputs.dry-run
    == null && 'true' || github.event.inputs.dry-run }}
  FORCE: ${{ github.event_name == 'push' || github.event.inputs.force == null && 'false'
    ||  github.event.inputs.force }}
  GITREF: ${{ github.event.inputs.gitref || github.ref }}
  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
jobs:
  publish-cdk:
    name: Publish Java CDK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event.inputs.comment-id
      name: Link comment to Workflow Run
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '> :clock2: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

          '
        comment-id: ${{ github.event.inputs.comment-id }}
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITREF }}
    - continue-on-error: true
      id: read-target-java-cdk-version
      name: Read Target Java CDK version
      run: "cdk_version=$(cat $CDK_VERSION_FILE_PATH | tr -d '\\n')\necho \"CDK_VERSION=$CDK_VERSION\"\
        \necho \"FORCE=$FORCE\"\necho \"DRY_RUN=$DRY_RUN\"\nif [[ -z \"$cdk_version\"\
        \ ]]; then\n  echo \"Failed to retrieve CDK version from $CDK_VERSION_FILE_PATH\"\
        \n  exit 1\nfi\necho \"CDK_VERSION=${cdk_version}\" >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Docker login
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    - continue-on-error: true
      env:
        CI: true
      name: Build Java CDK
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkBuild
        concurrent: true
        gradle-distribution-sha-256-sum-warning: false
        job-id: cdk-publish
        read-only: ${{ !(env.DRY_RUN == 'false') }}
    - continue-on-error: true
      env:
        CI: true
      if: ${{ (env.FORCE != 'true') }}
      name: Check for Existing Version
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --scan :airbyte-cdk:java:airbyte-cdk:assertCdkVersionNotPublished
        concurrent: true
        gradle-distribution-sha-256-sum-warning: false
        job-id: cdk-publish
        read-only: true
    - continue-on-error: true
      env:
        CI: true
        CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
        CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
      if: ${{ env.DRY_RUN == 'false' }}
      name: Publish Poms and Jars to CloudRepo
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --scan :airbyte-cdk:java:airbyte-cdk:cdkPublish
        concurrent: true
        execution-only-caches: true
        gradle-distribution-sha-256-sum-warning: false
        job-id: cdk-publish
        read-only: true
    - continue-on-error: true
      if: github.event.inputs.comment-id && success()
      name: Add Success Comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '> :white_check_mark: Successfully published Java CDK ${{ env.CDK_VERSION
          }}!

          '
        comment-id: ${{ github.event.inputs.comment-id }}
        edit-mode: append
    - continue-on-error: true
      if: github.event.inputs.comment-id && failure()
      name: Add Failure Comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '> :x: Publish Java CDK ${{ env.CDK_VERSION }} failed!

          '
        comment-id: ${{ github.event.inputs.comment-id }}
        edit-mode: append
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ env.DRY_RUN == 'false' && failure() }}
      name: Post failure to Slack channel
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"Error during `publish-cdk` while publishing Java\
          \ CDK!\",\n    \"blocks\": [\n        {\n            \"type\": \"section\"\
          ,\n            \"text\": {\n                \"type\": \"mrkdwn\",\n    \
          \            \"text\": \"Error while publishing Java CDK!\"\n          \
          \  }\n        },\n        {\n            \"type\": \"section\",\n      \
          \      \"text\": {\n                \"type\": \"mrkdwn\",\n            \
          \    \"text\": \"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      if: ${{ env.DRY_RUN == 'false' && !failure() }}
      name: Post success to Slack channel
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04J1M66D8B
        payload: "{\n    \"text\": \"New `${{ env.CDK_VERSION }}` version of Java\
          \ CDK was successfully published!\",\n    \"blocks\": [\n        {\n   \
          \         \"type\": \"section\",\n            \"text\": {\n            \
          \    \"type\": \"mrkdwn\",\n                \"text\": \"Java CDK ${{ env.CDK_VERSION\
          \ }} published successfully!\"\n            }\n        },\n        {\n \
          \           \"type\": \"section\",\n            \"text\": {\n          \
          \      \"type\": \"mrkdwn\",\n                \"text\": \"See details on\
          \ <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\\\
          n\"\n            }\n        }\n    ]\n}\n"
    timeout-minutes: 30
name: Publish Java CDK
on:
  repository_dispatch:
    types: trigger-ga___publish-java-cdk-command.yml
