concurrency: release-airbyte
jobs:
  release-airbyte:
    needs:
    - start-release-airbyte-runner
    - release-airbyte-platform
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: airbyte
        ref: master
        repository: airbytehq/airbyte
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
    - continue-on-error: true
      env:
        PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
      id: bump_version
      name: Bump Version for Airbyte
      run: './tools/bin/bump_version.sh

        '
      working-directory: airbyte
    - continue-on-error: true
      name: Run run-ab-platform script to download artifacts from Airbyte Platform
      run: './run-ab-platform.sh --refresh

        ./run-ab-platform.sh --download

        '
      working-directory: airbyte
    - continue-on-error: true
      name: Auto Commit Version and Platform Artifacts into Airbyte
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump Airbyte version from ${{ steps.bump_version.outputs.PREV_VERSION
          }} to ${{ steps.bump_version.outputs.NEW_VERSION }}
        push_options: --force
        repository: airbyte
    - continue-on-error: true
      env:
        GIT_REVISION: ${{ steps.bump_version.outputs.GIT_REVISION }}
        PREV_VERSION: ${{ steps.bump_version.outputs.PREV_VERSION }}
      name: Generate Change Log for Airbyte
      run: 'CHANGELOG=`PAGER=cat git log v${PREV_VERSION}..${GIT_REVISION} --oneline
        --decorate=no`

        echo "CHANGELOG<<EOF" >> $GITHUB_ENV

        echo -e "$CHANGELOG" >> $GITHUB_ENV

        echo "EOF" >> $GITHUB_ENV

        echo $CHANGELOG

        '
      working-directory: airbyte
    - continue-on-error: true
      env:
        NEW_VERSION: ${{ steps.bump_version.outputs.NEW_VERSION }}
      id: create_release
      name: Create Release for Airbyte
      uses: ncipollo/release-action@v1
      with:
        body: ${{ env.CHANGELOG }}
        owner: airbytehq
        repo: airbyte
        tag: v${{ env.NEW_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
  release-airbyte-platform:
    needs:
    - start-release-airbyte-runner
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - continue-on-error: true
      name: Checkout Airbyte Platform
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: airbyte-platform
        ref: main
        repository: airbytehq/airbyte-platform
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
    - continue-on-error: true
      env:
        CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
        CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
      id: release_airbyte_platform
      name: Release Airbyte Platform
      run: './tools/bin/release_version.sh  # this script calls the bump_version.sh
        script

        '
      working-directory: airbyte-platform
    - continue-on-error: true
      name: Auto Commit Version for Airbyte Platform
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump Airbyte version from ${{ steps.release_airbyte_platform.outputs.PREV_VERSION
          }} to ${{ steps.release_airbyte_platform.outputs.NEW_VERSION }}
        repository: airbyte-platform
    - continue-on-error: true
      env:
        GIT_REVISION: ${{ steps.release_airbyte_platform.outputs.GIT_REVISION }}
        PREV_VERSION: ${{ steps.release_airbyte_platform.outputs.PREV_VERSION }}
      name: Generate Change Log for Airbyte Platform
      run: 'CHANGELOG=`PAGER=cat git log v${PREV_VERSION}..${GIT_REVISION} --oneline
        --decorate=no`

        echo "CHANGELOG<<EOF" >> $GITHUB_ENV

        echo -e "$CHANGELOG" >> $GITHUB_ENV

        echo "EOF" >> $GITHUB_ENV

        echo $CHANGELOG

        '
      working-directory: airbyte-platform
    - continue-on-error: true
      env:
        NEW_VERSION: ${{ steps.release_airbyte_platform.outputs.NEW_VERSION }}
      id: create_release
      name: Create Release for Airbyte Platform
      uses: ncipollo/release-action@v1
      with:
        body: ${{ env.CHANGELOG }}
        owner: airbytehq
        repo: airbyte-platform
        tag: v${{ env.NEW_VERSION }}
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
  release-octavia:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PART_TO_BUMP: ${{ github.event.inputs.partToBump }}
      id: release_octavia
      name: Release Octavia
      run: ./tools/bin/release_version_octavia.sh
  start-release-airbyte-runner:
    name: 'Release Airbyte: Start EC2 Runner'
    outputs:
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
      label: ${{ steps.start-ec2-runner.outputs.label }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check PAT rate limits
      run: "./tools/bin/find_non_rate_limited_PAT \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_OSS\
        \ }} \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}\n"
    - continue-on-error: true
      id: start-ec2-runner
      name: Start AWS Runner
      uses: ./.github/actions/start-aws-runner
      with:
        aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
        github-token: ${{ env.PAT }}
    timeout-minutes: 10
  stop-release-airbyte-runner:
    if: ${{ always() }}
    name: 'Release Airbyte: Stop EC2 Runner'
    needs:
    - start-release-airbyte-runner
    - release-airbyte
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        aws-region: us-east-2
        aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check PAT rate limits
      run: "./tools/bin/find_non_rate_limited_PAT \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_OSS\
        \ }} \\\n  ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}\n"
    - continue-on-error: true
      name: Stop EC2 runner
      uses: supertopher/ec2-github-runner@base64v1.0.10
      with:
        ec2-instance-id: ${{ needs.start-release-airbyte-runner.outputs.ec2-instance-id
          }}
        github-token: ${{ env.PAT }}
        label: ${{ needs.start-release-airbyte-runner.outputs.label }}
        mode: stop
    timeout-minutes: 10
name: Release Open Source Airbyte
on:
  repository_dispatch:
    types: trigger-ga___release-airbyte-os.yml
