jobs:
  run-mypy-on-modified-cdk-files:
    name: Run mypy on modified cdk files
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      run: pip install mypy==1.6.0
    - continue-on-error: true
      id: changed-py-files
      name: Get Python changed files
      uses: tj-actions/changed-files@v43
      with:
        files: airbyte-cdk/python/airbyte_cdk/**/*.py
    - continue-on-error: true
      if: steps.changed-py-files.outputs.any_changed == 'true'
      name: Run if any of the listed files above is changed
      run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --config-file
        airbyte-cdk/python/mypy.ini --install-types --non-interactive
name: Python CDK - Run mypy on modified cdk files
on:
  repository_dispatch:
    types: trigger-ga___run-mypy-on-modified-cdk-files.yml
