jobs:
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: getref
      name: Get PR repo and ref
      run: 'pr_info="$(curl ${{ github.event.issue.pull_request.url }})"

        echo ref="$(echo $pr_info | jq -r ''.head.ref'')" >> $GITHUB_OUTPUT

        echo repo="$(echo $pr_info | jq -r ''.head.repo.full_name'')" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: scd
      name: Slash Command Dispatch (Workflow)
      uses: peter-evans/slash-command-dispatch@v3
      with:
        commands: 'format-fix

          test

          test-performance

          publish-java-cdk

          connector-performance

          approve-regression-tests

          '
        dispatch-type: workflow
        permission: write
        static-args: 'repo=${{ steps.getref.outputs.repo }}

          gitref=${{ steps.getref.outputs.ref }}

          comment-id=${{ github.event.comment.id }}

          pr=${{ github.event.issue.number }}

          '
        token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
    - continue-on-error: true
      if: steps.scd.outputs.error-message
      name: Edit comment with error message
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: '> Error: ${{ steps.scd.outputs.error-message }}

          '
        comment-id: ${{ github.event.comment.id }}
name: Slash Command Dispatch
on:
  repository_dispatch:
    types: trigger-ga___slash-commands.yml
