jobs:
  terminate:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
        AWS_EC2_METADATA_DISABLED: true
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
      name: List and Terminate Instances Older Than 4 Hours
      run: "set -euxo pipefail\n\nexport TIME_LIMIT=14400 # 4 hours\n\naws configure\
        \ set default.region us-east-2\n\n# See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instances.html\
        \ for describe command.\n# Since the AWS cli returns an ISO HH:MM timestamp,\
        \ and Jq only accepts Z timestamps, we define a function toZ to convert this.\n\
        export to_terminate=$(aws ec2 describe-instances --no-paginate --filters --filters\
        \ 'Name=tag:Repository,Values=airbytehq/airbyte-platform-internal,airbytehq/airbyte-platform,airbytehq/airbyte'\
        \ Name=instance-state-name,Values=running \\\n  --query 'Reservations[*].Instances[*].{Instance:InstanceId,LaunchTime:LaunchTime}'\
        \ --output json \\\n| jq 'def toZ(str): str | (split(\"+\")[0] + \"Z\") |\
        \ fromdate ;\n    flatten | map( { InstanceId: .Instance, LaunchTime: toZ(.LaunchTime)\
        \ } ) | map( select ( .LaunchTime < (now - (env.TIME_LIMIT|tonumber)) ) )')\n\
        \necho \"MARKED FOR TERMINATION: ${to_terminate}\"\n\n# See https://docs.aws.amazon.com/cli/latest/reference/ec2/terminate-instances.html\
        \ for terminate command.\necho $to_terminate |  jq '.[]  | .InstanceId' |\
        \ xargs --no-run-if-empty --max-args=1 aws ec2 terminate-instances --instance-ids\n"
  terminate-github-instances:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
      name: List and Terminate GH actions in status 'offline'
      run: ./tools/bin/gh_action_zombie_killer
name: Terminate Zombie Build Instances
on:
  repository_dispatch:
    types: trigger-ga___terminate-zombie-build-instances.yml
