jobs:
  deploy-catalog-to-stage:
    name: Upload Metadata Files to Metadata Service
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Airbyte Cloud
      uses: actions/checkout@v2
    - continue-on-error: true
      id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v44
      with:
        files: airbyte-integrations/connectors/**/metadata.yaml
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Install metadata_service
      run: pip install airbyte-ci/connectors/metadata_service/lib
    - continue-on-error: true
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        GCS_CREDENTIALS: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Upload All Changed Metadata Files
      run: "for file in ${{ steps.changed-files.outputs.all_changed_files }}; do\n\
        \  metadata_service upload $file prod-airbyte-cloud-connector-metadata-service\n\
        done\n"
    - continue-on-error: true
      env:
        MSG_MINIMAL: true
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://avatars.slack-edge.com/temp/2020-09-01/1342729352468_209b10acd6ff13a649a1.jpg
        SLACK_MESSAGE: https://github.com/${{ github.repository }}/actions/runs/${{
          github.run_id }}
        SLACK_TITLE: Failed to upload metadata file
        SLACK_USERNAME: Metadata Service
        SLACK_WEBHOOK: ${{ secrets.PUBLISH_ON_MERGE_SLACK_WEBHOOK }}
      if: failure()
      name: Slack Notification - Failure
      uses: rtCamp/action-slack-notify@master
name: Connector Ops CI - Upload Changed Metadata Files [Emergency Use!]
on:
  repository_dispatch:
    types: trigger-ga___upload-metadata-files.yml
