jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout repo content
      uses: actions/checkout@v3
    - continue-on-error: true
      name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13
    - continue-on-error: true
      name: install python packages
      run: 'python -m pip install --upgrade pip

        pip install PyGithub slack_sdk

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: execute cleanup workflow py script
      run: python tools/bin/cleanup-workflow-runs.py --delete
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
      name: execute dormant workflow py script
      run: python tools/bin/identify-dormant-workflows.py
name: Cleanup old GH workflow runs
on:
  repository_dispatch:
    types: trigger-ga___workflow-cleanup.yml
